on:
  push:
    paths:
      - 'pages/**'
      - '.github/workflows/pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish app
        uses: WalshyDev/wrangler-action@walshy/pages-996-support-wrangler2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=direct-uploads
          wranglerVersion: beta
          workingDirectory: pages
