on:
  push:
    paths:
      - 'worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish app
        uses: WalshyDev/wrangler-action@walshy/pages-996-support-wrangler2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
          workingDirectory: worker
          secrets: |
            SECRET
        env:
          SECRET: ${{ github.run_id	}}